"""Auto-generated migration.

Created: 2026-06-03 13:35:54
"""

depends_on = None


def upgrade(ctx):
    """Apply migration."""
    ctx.create_table(
        "video_file",
        fields=[
            {
                "name": "path",
                "python_type": "str",
                "db_type": "TEXT",
                "nullable": False,
                "primary_key": True,
                "unique": False,
                "default": None,
                "auto_increment": False,
                "max_length": None,
                "max_digits": None,
                "decimal_places": None,
            },
            {
                "name": "size_bytes",
                "python_type": "int",
                "db_type": None,
                "nullable": False,
                "primary_key": False,
                "unique": False,
                "default": None,
                "auto_increment": False,
                "max_length": None,
                "max_digits": None,
                "decimal_places": None,
            },
            {
                "name": "mtime_ns",
                "python_type": "int",
                "db_type": None,
                "nullable": False,
                "primary_key": False,
                "unique": False,
                "default": None,
                "auto_increment": False,
                "max_length": None,
                "max_digits": None,
                "decimal_places": None,
            },
        ],
    )
    ctx.create_table(
        "ardetector",
        fields=[
            {
                "name": "id",
                "python_type": "int",
                "db_type": None,
                "nullable": True,
                "primary_key": True,
                "unique": False,
                "default": None,
                "auto_increment": False,
                "max_length": None,
                "max_digits": None,
                "decimal_places": None,
            },
            {
                "name": "error",
                "python_type": "str",
                "db_type": "TEXT",
                "nullable": True,
                "primary_key": False,
                "unique": False,
                "default": None,
                "auto_increment": False,
                "max_length": None,
                "max_digits": None,
                "decimal_places": None,
            },
            {
                "name": "aspect_primary",
                "python_type": "float",
                "db_type": None,
                "nullable": True,
                "primary_key": False,
                "unique": False,
                "default": None,
                "auto_increment": False,
                "max_length": None,
                "max_digits": None,
                "decimal_places": None,
            },
            {
                "name": "aspect_widest",
                "python_type": "float",
                "db_type": None,
                "nullable": True,
                "primary_key": False,
                "unique": False,
                "default": None,
                "auto_increment": False,
                "max_length": None,
                "max_digits": None,
                "decimal_places": None,
            },
            {
                "name": "aspect_samples",
                "python_type": "str",
                "db_type": "TEXT",
                "nullable": True,
                "primary_key": False,
                "unique": False,
                "default": None,
                "auto_increment": False,
                "max_length": None,
                "max_digits": None,
                "decimal_places": None,
            },
            {
                "name": "color_pct",
                "python_type": "float",
                "db_type": None,
                "nullable": True,
                "primary_key": False,
                "unique": False,
                "default": None,
                "auto_increment": False,
                "max_length": None,
                "max_digits": None,
                "decimal_places": None,
            },
            {
                "name": "video_path",
                "python_type": "str",
                "db_type": None,
                "nullable": False,
                "primary_key": False,
                "unique": False,
                "default": None,
                "auto_increment": False,
                "max_length": None,
                "max_digits": None,
                "decimal_places": None,
            },
        ],
        indexes=[
            {
                "name": "ardetector_video_uq",
                "fields": ["video_path"],
                "unique": True,
                "method": None,
            }
        ],
        foreign_keys=[
            {
                "name": "fk_ardetector_video_path",
                "columns": ["video_path"],
                "ref_table": "video_file",
                "ref_columns": ["path"],
                "on_delete": "CASCADE",
                "on_update": "CASCADE",
            }
        ],
    )
    ctx.create_table(
        "audio_track",
        fields=[
            {
                "name": "id",
                "python_type": "int",
                "db_type": None,
                "nullable": True,
                "primary_key": True,
                "unique": False,
                "default": None,
                "auto_increment": False,
                "max_length": None,
                "max_digits": None,
                "decimal_places": None,
            },
            {
                "name": "idx",
                "python_type": "int",
                "db_type": None,
                "nullable": False,
                "primary_key": False,
                "unique": False,
                "default": None,
                "auto_increment": False,
                "max_length": None,
                "max_digits": None,
                "decimal_places": None,
            },
            {
                "name": "codec",
                "python_type": "str",
                "db_type": "TEXT",
                "nullable": True,
                "primary_key": False,
                "unique": False,
                "default": None,
                "auto_increment": False,
                "max_length": None,
                "max_digits": None,
                "decimal_places": None,
            },
            {
                "name": "channels",
                "python_type": "int",
                "db_type": None,
                "nullable": True,
                "primary_key": False,
                "unique": False,
                "default": None,
                "auto_increment": False,
                "max_length": None,
                "max_digits": None,
                "decimal_places": None,
            },
            {
                "name": "layout",
                "python_type": "str",
                "db_type": "TEXT",
                "nullable": True,
                "primary_key": False,
                "unique": False,
                "default": None,
                "auto_increment": False,
                "max_length": None,
                "max_digits": None,
                "decimal_places": None,
            },
            {
                "name": "language",
                "python_type": "str",
                "db_type": "TEXT",
                "nullable": True,
                "primary_key": False,
                "unique": False,
                "default": None,
                "auto_increment": False,
                "max_length": None,
                "max_digits": None,
                "decimal_places": None,
            },
            {
                "name": "title",
                "python_type": "str",
                "db_type": "TEXT",
                "nullable": True,
                "primary_key": False,
                "unique": False,
                "default": None,
                "auto_increment": False,
                "max_length": None,
                "max_digits": None,
                "decimal_places": None,
            },
            {
                "name": "is_default",
                "python_type": "bool",
                "db_type": None,
                "nullable": False,
                "primary_key": False,
                "unique": False,
                "default": "0",
                "auto_increment": False,
                "max_length": None,
                "max_digits": None,
                "decimal_places": None,
            },
            {
                "name": "is_forced",
                "python_type": "bool",
                "db_type": None,
                "nullable": False,
                "primary_key": False,
                "unique": False,
                "default": "0",
                "auto_increment": False,
                "max_length": None,
                "max_digits": None,
                "decimal_places": None,
            },
            {
                "name": "format",
                "python_type": "str",
                "db_type": "TEXT",
                "nullable": True,
                "primary_key": False,
                "unique": False,
                "default": None,
                "auto_increment": False,
                "max_length": None,
                "max_digits": None,
                "decimal_places": None,
            },
            {
                "name": "commercial_name",
                "python_type": "str",
                "db_type": "TEXT",
                "nullable": True,
                "primary_key": False,
                "unique": False,
                "default": None,
                "auto_increment": False,
                "max_length": None,
                "max_digits": None,
                "decimal_places": None,
            },
            {
                "name": "bit_rate",
                "python_type": "int",
                "db_type": None,
                "nullable": True,
                "primary_key": False,
                "unique": False,
                "default": None,
                "auto_increment": False,
                "max_length": None,
                "max_digits": None,
                "decimal_places": None,
            },
            {
                "name": "bit_rate_mode",
                "python_type": "str",
                "db_type": "TEXT",
                "nullable": True,
                "primary_key": False,
                "unique": False,
                "default": None,
                "auto_increment": False,
                "max_length": None,
                "max_digits": None,
                "decimal_places": None,
            },
            {
                "name": "sample_rate",
                "python_type": "int",
                "db_type": None,
                "nullable": True,
                "primary_key": False,
                "unique": False,
                "default": None,
                "auto_increment": False,
                "max_length": None,
                "max_digits": None,
                "decimal_places": None,
            },
            {
                "name": "bit_depth",
                "python_type": "int",
                "db_type": None,
                "nullable": True,
                "primary_key": False,
                "unique": False,
                "default": None,
                "auto_increment": False,
                "max_length": None,
                "max_digits": None,
                "decimal_places": None,
            },
            {
                "name": "compression_mode",
                "python_type": "str",
                "db_type": "TEXT",
                "nullable": True,
                "primary_key": False,
                "unique": False,
                "default": None,
                "auto_increment": False,
                "max_length": None,
                "max_digits": None,
                "decimal_places": None,
            },
            {
                "name": "video_path",
                "python_type": "str",
                "db_type": None,
                "nullable": False,
                "primary_key": False,
                "unique": False,
                "default": None,
                "auto_increment": False,
                "max_length": None,
                "max_digits": None,
                "decimal_places": None,
            },
        ],
        indexes=[
            {
                "name": "audio_track_uq",
                "fields": ["video_path", "idx"],
                "unique": True,
                "method": None,
            }
        ],
        foreign_keys=[
            {
                "name": "fk_audio_track_video_path",
                "columns": ["video_path"],
                "ref_table": "video_file",
                "ref_columns": ["path"],
                "on_delete": "CASCADE",
                "on_update": "CASCADE",
            }
        ],
    )
    ctx.create_table(
        "mediainfo",
        fields=[
            {
                "name": "id",
                "python_type": "int",
                "db_type": None,
                "nullable": True,
                "primary_key": True,
                "unique": False,
                "default": None,
                "auto_increment": False,
                "max_length": None,
                "max_digits": None,
                "decimal_places": None,
            },
            {
                "name": "error",
                "python_type": "str",
                "db_type": "TEXT",
                "nullable": True,
                "primary_key": False,
                "unique": False,
                "default": None,
                "auto_increment": False,
                "max_length": None,
                "max_digits": None,
                "decimal_places": None,
            },
            {
                "name": "container",
                "python_type": "str",
                "db_type": "TEXT",
                "nullable": True,
                "primary_key": False,
                "unique": False,
                "default": None,
                "auto_increment": False,
                "max_length": None,
                "max_digits": None,
                "decimal_places": None,
            },
            {
                "name": "duration",
                "python_type": "float",
                "db_type": None,
                "nullable": True,
                "primary_key": False,
                "unique": False,
                "default": None,
                "auto_increment": False,
                "max_length": None,
                "max_digits": None,
                "decimal_places": None,
            },
            {
                "name": "video_codec",
                "python_type": "str",
                "db_type": "TEXT",
                "nullable": True,
                "primary_key": False,
                "unique": False,
                "default": None,
                "auto_increment": False,
                "max_length": None,
                "max_digits": None,
                "decimal_places": None,
            },
            {
                "name": "video_profile",
                "python_type": "str",
                "db_type": "TEXT",
                "nullable": True,
                "primary_key": False,
                "unique": False,
                "default": None,
                "auto_increment": False,
                "max_length": None,
                "max_digits": None,
                "decimal_places": None,
            },
            {
                "name": "video_width",
                "python_type": "int",
                "db_type": None,
                "nullable": True,
                "primary_key": False,
                "unique": False,
                "default": None,
                "auto_increment": False,
                "max_length": None,
                "max_digits": None,
                "decimal_places": None,
            },
            {
                "name": "video_height",
                "python_type": "int",
                "db_type": None,
                "nullable": True,
                "primary_key": False,
                "unique": False,
                "default": None,
                "auto_increment": False,
                "max_length": None,
                "max_digits": None,
                "decimal_places": None,
            },
            {
                "name": "video_bit_depth",
                "python_type": "int",
                "db_type": None,
                "nullable": True,
                "primary_key": False,
                "unique": False,
                "default": None,
                "auto_increment": False,
                "max_length": None,
                "max_digits": None,
                "decimal_places": None,
            },
            {
                "name": "video_hdr",
                "python_type": "str",
                "db_type": "TEXT",
                "nullable": True,
                "primary_key": False,
                "unique": False,
                "default": None,
                "auto_increment": False,
                "max_length": None,
                "max_digits": None,
                "decimal_places": None,
            },
            {
                "name": "video_hdr_format",
                "python_type": "str",
                "db_type": "TEXT",
                "nullable": True,
                "primary_key": False,
                "unique": False,
                "default": None,
                "auto_increment": False,
                "max_length": None,
                "max_digits": None,
                "decimal_places": None,
            },
            {
                "name": "video_frame_rate",
                "python_type": "float",
                "db_type": None,
                "nullable": True,
                "primary_key": False,
                "unique": False,
                "default": None,
                "auto_increment": False,
                "max_length": None,
                "max_digits": None,
                "decimal_places": None,
            },
            {
                "name": "video_bit_rate",
                "python_type": "int",
                "db_type": None,
                "nullable": True,
                "primary_key": False,
                "unique": False,
                "default": None,
                "auto_increment": False,
                "max_length": None,
                "max_digits": None,
                "decimal_places": None,
            },
            {
                "name": "video_max_bit_rate",
                "python_type": "int",
                "db_type": None,
                "nullable": True,
                "primary_key": False,
                "unique": False,
                "default": None,
                "auto_increment": False,
                "max_length": None,
                "max_digits": None,
                "decimal_places": None,
            },
            {
                "name": "video_path",
                "python_type": "str",
                "db_type": None,
                "nullable": False,
                "primary_key": False,
                "unique": False,
                "default": None,
                "auto_increment": False,
                "max_length": None,
                "max_digits": None,
                "decimal_places": None,
            },
        ],
        indexes=[
            {
                "name": "mediainfo_video_uq",
                "fields": ["video_path"],
                "unique": True,
                "method": None,
            }
        ],
        foreign_keys=[
            {
                "name": "fk_mediainfo_video_path",
                "columns": ["video_path"],
                "ref_table": "video_file",
                "ref_columns": ["path"],
                "on_delete": "CASCADE",
                "on_update": "CASCADE",
            }
        ],
    )
    ctx.create_table(
        "movie",
        fields=[
            {
                "name": "id",
                "python_type": "int",
                "db_type": None,
                "nullable": False,
                "primary_key": True,
                "unique": False,
                "default": None,
                "auto_increment": False,
                "max_length": None,
                "max_digits": None,
                "decimal_places": None,
            },
            {
                "name": "tmdb_id",
                "python_type": "int",
                "db_type": None,
                "nullable": True,
                "primary_key": False,
                "unique": False,
                "default": None,
                "auto_increment": False,
                "max_length": None,
                "max_digits": None,
                "decimal_places": None,
            },
            {
                "name": "video_path",
                "python_type": "str",
                "db_type": None,
                "nullable": False,
                "primary_key": False,
                "unique": False,
                "default": None,
                "auto_increment": False,
                "max_length": None,
                "max_digits": None,
                "decimal_places": None,
            },
        ],
        foreign_keys=[
            {
                "name": "fk_movie_video_path",
                "columns": ["video_path"],
                "ref_table": "video_file",
                "ref_columns": ["path"],
                "on_delete": "CASCADE",
                "on_update": "CASCADE",
            }
        ],
    )
    ctx.create_table(
        "plex_item",
        fields=[
            {
                "name": "rating_key",
                "python_type": "str",
                "db_type": "TEXT",
                "nullable": False,
                "primary_key": True,
                "unique": False,
                "default": None,
                "auto_increment": False,
                "max_length": None,
                "max_digits": None,
                "decimal_places": None,
            },
            {
                "name": "type",
                "python_type": "str",
                "db_type": "TEXT",
                "nullable": False,
                "primary_key": False,
                "unique": False,
                "default": None,
                "auto_increment": False,
                "max_length": None,
                "max_digits": None,
                "decimal_places": None,
            },
            {
                "name": "title",
                "python_type": "str",
                "db_type": "TEXT",
                "nullable": True,
                "primary_key": False,
                "unique": False,
                "default": None,
                "auto_increment": False,
                "max_length": None,
                "max_digits": None,
                "decimal_places": None,
            },
            {
                "name": "year",
                "python_type": "int",
                "db_type": None,
                "nullable": True,
                "primary_key": False,
                "unique": False,
                "default": None,
                "auto_increment": False,
                "max_length": None,
                "max_digits": None,
                "decimal_places": None,
            },
            {
                "name": "show_title",
                "python_type": "str",
                "db_type": "TEXT",
                "nullable": True,
                "primary_key": False,
                "unique": False,
                "default": None,
                "auto_increment": False,
                "max_length": None,
                "max_digits": None,
                "decimal_places": None,
            },
            {
                "name": "season_number",
                "python_type": "int",
                "db_type": None,
                "nullable": True,
                "primary_key": False,
                "unique": False,
                "default": None,
                "auto_increment": False,
                "max_length": None,
                "max_digits": None,
                "decimal_places": None,
            },
            {
                "name": "episode_number",
                "python_type": "int",
                "db_type": None,
                "nullable": True,
                "primary_key": False,
                "unique": False,
                "default": None,
                "auto_increment": False,
                "max_length": None,
                "max_digits": None,
                "decimal_places": None,
            },
            {
                "name": "video_path",
                "python_type": "str",
                "db_type": None,
                "nullable": False,
                "primary_key": False,
                "unique": False,
                "default": None,
                "auto_increment": False,
                "max_length": None,
                "max_digits": None,
                "decimal_places": None,
            },
        ],
        foreign_keys=[
            {
                "name": "fk_plex_item_video_path",
                "columns": ["video_path"],
                "ref_table": "video_file",
                "ref_columns": ["path"],
                "on_delete": "CASCADE",
                "on_update": "CASCADE",
            }
        ],
    )
    ctx.create_table(
        "subtitle_file",
        fields=[
            {
                "name": "path",
                "python_type": "str",
                "db_type": "TEXT",
                "nullable": False,
                "primary_key": True,
                "unique": False,
                "default": None,
                "auto_increment": False,
                "max_length": None,
                "max_digits": None,
                "decimal_places": None,
            },
            {
                "name": "size_bytes",
                "python_type": "int",
                "db_type": None,
                "nullable": False,
                "primary_key": False,
                "unique": False,
                "default": None,
                "auto_increment": False,
                "max_length": None,
                "max_digits": None,
                "decimal_places": None,
            },
            {
                "name": "mtime_ns",
                "python_type": "int",
                "db_type": None,
                "nullable": False,
                "primary_key": False,
                "unique": False,
                "default": None,
                "auto_increment": False,
                "max_length": None,
                "max_digits": None,
                "decimal_places": None,
            },
            {
                "name": "video_path",
                "python_type": "str",
                "db_type": None,
                "nullable": False,
                "primary_key": False,
                "unique": False,
                "default": None,
                "auto_increment": False,
                "max_length": None,
                "max_digits": None,
                "decimal_places": None,
            },
        ],
        foreign_keys=[
            {
                "name": "fk_subtitle_file_video_path",
                "columns": ["video_path"],
                "ref_table": "video_file",
                "ref_columns": ["path"],
                "on_delete": "CASCADE",
                "on_update": "CASCADE",
            }
        ],
    )
    ctx.create_table(
        "subtitle_track_external",
        fields=[
            {
                "name": "id",
                "python_type": "int",
                "db_type": None,
                "nullable": True,
                "primary_key": True,
                "unique": False,
                "default": None,
                "auto_increment": False,
                "max_length": None,
                "max_digits": None,
                "decimal_places": None,
            },
            {
                "name": "idx",
                "python_type": "int",
                "db_type": None,
                "nullable": False,
                "primary_key": False,
                "unique": False,
                "default": None,
                "auto_increment": False,
                "max_length": None,
                "max_digits": None,
                "decimal_places": None,
            },
            {
                "name": "codec",
                "python_type": "str",
                "db_type": "TEXT",
                "nullable": True,
                "primary_key": False,
                "unique": False,
                "default": None,
                "auto_increment": False,
                "max_length": None,
                "max_digits": None,
                "decimal_places": None,
            },
            {
                "name": "language",
                "python_type": "str",
                "db_type": "TEXT",
                "nullable": True,
                "primary_key": False,
                "unique": False,
                "default": None,
                "auto_increment": False,
                "max_length": None,
                "max_digits": None,
                "decimal_places": None,
            },
            {
                "name": "title",
                "python_type": "str",
                "db_type": "TEXT",
                "nullable": True,
                "primary_key": False,
                "unique": False,
                "default": None,
                "auto_increment": False,
                "max_length": None,
                "max_digits": None,
                "decimal_places": None,
            },
            {
                "name": "is_default",
                "python_type": "bool",
                "db_type": None,
                "nullable": False,
                "primary_key": False,
                "unique": False,
                "default": "0",
                "auto_increment": False,
                "max_length": None,
                "max_digits": None,
                "decimal_places": None,
            },
            {
                "name": "is_forced",
                "python_type": "bool",
                "db_type": None,
                "nullable": False,
                "primary_key": False,
                "unique": False,
                "default": "0",
                "auto_increment": False,
                "max_length": None,
                "max_digits": None,
                "decimal_places": None,
            },
            {
                "name": "is_sdh",
                "python_type": "bool",
                "db_type": None,
                "nullable": False,
                "primary_key": False,
                "unique": False,
                "default": "0",
                "auto_increment": False,
                "max_length": None,
                "max_digits": None,
                "decimal_places": None,
            },
            {
                "name": "subtitle_path",
                "python_type": "str",
                "db_type": None,
                "nullable": False,
                "primary_key": False,
                "unique": False,
                "default": None,
                "auto_increment": False,
                "max_length": None,
                "max_digits": None,
                "decimal_places": None,
            },
        ],
        indexes=[
            {
                "name": "subtitle_external_uq",
                "fields": ["subtitle_path", "idx"],
                "unique": True,
                "method": None,
            }
        ],
        foreign_keys=[
            {
                "name": "fk_subtitle_track_external_subtitle_path",
                "columns": ["subtitle_path"],
                "ref_table": "subtitle_file",
                "ref_columns": ["path"],
                "on_delete": "CASCADE",
                "on_update": "CASCADE",
            }
        ],
    )
    ctx.create_table(
        "subtitle_track_internal",
        fields=[
            {
                "name": "id",
                "python_type": "int",
                "db_type": None,
                "nullable": True,
                "primary_key": True,
                "unique": False,
                "default": None,
                "auto_increment": False,
                "max_length": None,
                "max_digits": None,
                "decimal_places": None,
            },
            {
                "name": "idx",
                "python_type": "int",
                "db_type": None,
                "nullable": False,
                "primary_key": False,
                "unique": False,
                "default": None,
                "auto_increment": False,
                "max_length": None,
                "max_digits": None,
                "decimal_places": None,
            },
            {
                "name": "codec",
                "python_type": "str",
                "db_type": "TEXT",
                "nullable": True,
                "primary_key": False,
                "unique": False,
                "default": None,
                "auto_increment": False,
                "max_length": None,
                "max_digits": None,
                "decimal_places": None,
            },
            {
                "name": "language",
                "python_type": "str",
                "db_type": "TEXT",
                "nullable": True,
                "primary_key": False,
                "unique": False,
                "default": None,
                "auto_increment": False,
                "max_length": None,
                "max_digits": None,
                "decimal_places": None,
            },
            {
                "name": "title",
                "python_type": "str",
                "db_type": "TEXT",
                "nullable": True,
                "primary_key": False,
                "unique": False,
                "default": None,
                "auto_increment": False,
                "max_length": None,
                "max_digits": None,
                "decimal_places": None,
            },
            {
                "name": "is_default",
                "python_type": "bool",
                "db_type": None,
                "nullable": False,
                "primary_key": False,
                "unique": False,
                "default": "0",
                "auto_increment": False,
                "max_length": None,
                "max_digits": None,
                "decimal_places": None,
            },
            {
                "name": "is_forced",
                "python_type": "bool",
                "db_type": None,
                "nullable": False,
                "primary_key": False,
                "unique": False,
                "default": "0",
                "auto_increment": False,
                "max_length": None,
                "max_digits": None,
                "decimal_places": None,
            },
            {
                "name": "is_sdh",
                "python_type": "bool",
                "db_type": None,
                "nullable": False,
                "primary_key": False,
                "unique": False,
                "default": "0",
                "auto_increment": False,
                "max_length": None,
                "max_digits": None,
                "decimal_places": None,
            },
            {
                "name": "video_path",
                "python_type": "str",
                "db_type": None,
                "nullable": False,
                "primary_key": False,
                "unique": False,
                "default": None,
                "auto_increment": False,
                "max_length": None,
                "max_digits": None,
                "decimal_places": None,
            },
        ],
        indexes=[
            {
                "name": "subtitle_internal_uq",
                "fields": ["video_path", "idx"],
                "unique": True,
                "method": None,
            }
        ],
        foreign_keys=[
            {
                "name": "fk_subtitle_track_internal_video_path",
                "columns": ["video_path"],
                "ref_table": "video_file",
                "ref_columns": ["path"],
                "on_delete": "CASCADE",
                "on_update": "CASCADE",
            }
        ],
    )
    ctx.create_table(
        "series",
        fields=[
            {
                "name": "id",
                "python_type": "int",
                "db_type": None,
                "nullable": False,
                "primary_key": True,
                "unique": False,
                "default": None,
                "auto_increment": False,
                "max_length": None,
                "max_digits": None,
                "decimal_places": None,
            },
            {
                "name": "video_folder",
                "python_type": "str",
                "db_type": "TEXT",
                "nullable": False,
                "primary_key": False,
                "unique": False,
                "default": None,
                "auto_increment": False,
                "max_length": None,
                "max_digits": None,
                "decimal_places": None,
            },
            {
                "name": "title_slug",
                "python_type": "str",
                "db_type": "TEXT",
                "nullable": True,
                "primary_key": False,
                "unique": False,
                "default": None,
                "auto_increment": False,
                "max_length": None,
                "max_digits": None,
                "decimal_places": None,
            },
        ],
    )
    ctx.create_table(
        "plex_auth",
        fields=[
            {
                "name": "id",
                "python_type": "int",
                "db_type": None,
                "nullable": False,
                "primary_key": True,
                "unique": False,
                "default": None,
                "auto_increment": False,
                "max_length": None,
                "max_digits": None,
                "decimal_places": None,
            },
            {
                "name": "client_id",
                "python_type": "str",
                "db_type": "TEXT",
                "nullable": True,
                "primary_key": False,
                "unique": False,
                "default": None,
                "auto_increment": False,
                "max_length": None,
                "max_digits": None,
                "decimal_places": None,
            },
            {
                "name": "token",
                "python_type": "str",
                "db_type": "TEXT",
                "nullable": True,
                "primary_key": False,
                "unique": False,
                "default": None,
                "auto_increment": False,
                "max_length": None,
                "max_digits": None,
                "decimal_places": None,
            },
            {
                "name": "server_url",
                "python_type": "str",
                "db_type": "TEXT",
                "nullable": True,
                "primary_key": False,
                "unique": False,
                "default": None,
                "auto_increment": False,
                "max_length": None,
                "max_digits": None,
                "decimal_places": None,
            },
            {
                "name": "server_name",
                "python_type": "str",
                "db_type": "TEXT",
                "nullable": True,
                "primary_key": False,
                "unique": False,
                "default": None,
                "auto_increment": False,
                "max_length": None,
                "max_digits": None,
                "decimal_places": None,
            },
            {
                "name": "machine_id",
                "python_type": "str",
                "db_type": "TEXT",
                "nullable": True,
                "primary_key": False,
                "unique": False,
                "default": None,
                "auto_increment": False,
                "max_length": None,
                "max_digits": None,
                "decimal_places": None,
            },
        ],
    )


def downgrade(ctx):
    """Revert migration."""
    ctx.drop_table("plex_auth")
    ctx.drop_table("series")
    ctx.drop_table("subtitle_track_internal")
    ctx.drop_table("subtitle_track_external")
    ctx.drop_table("subtitle_file")
    ctx.drop_table("plex_item")
    ctx.drop_table("movie")
    ctx.drop_table("mediainfo")
    ctx.drop_table("audio_track")
    ctx.drop_table("ardetector")
    ctx.drop_table("video_file")
